config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  resources :todos do
    resource :completion, only: [:create, :destroy]
  end
  resource :session, only: [:new, :create]
end

app/models/todo.rb
# Todo class
class Todo < ActiveRecord::Base
  def completed?
    completed_at?
  end

  def complete!
    touch :completed_at
  end

  def incomplete!
    update_column :completed_at, nil
  end
end

app/models/user.rb
class User
  def initialize(email)
    @email = email
  end

  def todos
    Todo.where(email: @email)
  end

  def signed_in?
    @email.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate
    if ! signed_in?
      redirect_to new_session_path
    end
  end

  def signed_in?
    current_user.signed_in?
  end

  def sign_in_as(email)
    session[:current_email] = email
  end

  def current_user
    User.new(session[:current_email])
  end
end

app/controllers/completions_controller.rb
# Completions controller
class CompletionsController < ApplicationController
  def create
    todo.complete!
    redirect_to todos_path
  end

  def destroy
    todo.incomplete!
    redirect_to todos_path
  end

  private

  def todo
    current_user.todos.find(params[:todo_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    sign_in_as params[:session][:email]
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
# Todos controller
class TodosController < ApplicationController
  before_filter :authenticate

  def index
    @todos = current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = current_user.todos.create(todo_params)
    if @todo.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<h1>Todos</h1>
<%= link_to "New Todo", new_todo_path %>

<ol class="todos">
  <% @todos.each do |todo| %>
    <li class=<%= "completed" if todo.completed? %>>
      <%= todo.name %>
      <% if todo.completed? %>
        <%= button_to "Mark Incomplete", todo_completion_path(todo), method: :delete %>
      <% else %>
        <%= button_to "Mark Completed", todo_completion_path(todo) %>
      <% end %>
    </li>
  <% end %>
</ol>

app/views/todos/new.html.erb
<%= form_for @todo do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Create Todo" %>
<% end %>